/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package augusto.prog3.vista;

import augusto.prog3.modelo.implementaciones.Habitacion;
import augusto.prog3.modelo.implementaciones.Hotel3;
import augusto.prog3.modelo.implementaciones.Hotel4;
import augusto.prog3.modelo.implementaciones.Hotel5;
import augusto.prog3.modelo.implementaciones.Huesped;
import augusto.prog3.modelo.implementaciones.ServicioAdicional;
import augusto.prog3.servicio.HotelService;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Augusto
 */
public class Vista1 extends javax.swing.JFrame {

    /**
     * Creates new form Vista1
     */
    public Vista1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    List<Huesped> huespedes = new ArrayList<>();
    Hotel3 hotel3 = new Hotel3();
    Hotel4 hotel4 = new Hotel4();
    Hotel5 hotel5 = new Hotel5();
    HotelService servicio3 = new HotelService(hotel3);
    HotelService servicio4 = new HotelService(hotel4);
    HotelService servicio5 = new HotelService(hotel5);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelAlojamiento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbx_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbx_nroid = new javax.swing.JTextField();
        btn_addHuesped = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_huespedes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cbx_hoteles = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cld_llegada = new com.toedter.calendar.JDateChooser();
        cld_salida = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_alojar = new javax.swing.JButton();
        cbx_tipohabitacion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbx_titular = new javax.swing.JComboBox<>();
        panelServicios = new javax.swing.JPanel();
        panelCaja = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ComodINN");

        panelAlojamiento.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setText("Nombre completo");

        jLabel2.setText("Nro. Identificación");

        btn_addHuesped.setText("Añadir huesped");
        btn_addHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addHuespedActionPerformed(evt);
            }
        });

        txt_huespedes.setColumns(20);
        txt_huespedes.setRows(5);
        jScrollPane1.setViewportView(txt_huespedes);

        jLabel3.setText("Lista de huéspedes");

        cbx_hoteles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3 estrellas", "4 estrellas", "5 estrellas" }));
        cbx_hoteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_hotelesMouseClicked(evt);
            }
        });
        cbx_hoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_hotelesActionPerformed(evt);
            }
        });
        cbx_hoteles.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbx_hotelesPropertyChange(evt);
            }
        });

        jLabel4.setText("Hoteles");

        cld_llegada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cld_llegadaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cld_llegadaMouseExited(evt);
            }
        });

        jLabel5.setText("Fecha de llegada");

        jLabel6.setText("Fecha de salida");

        btn_alojar.setText("Agendar alojamiento");
        btn_alojar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alojarActionPerformed(evt);
            }
        });

        cbx_tipohabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Tipo de habitación");

        jLabel9.setText("Titular del alojamiento");

        javax.swing.GroupLayout panelAlojamientoLayout = new javax.swing.GroupLayout(panelAlojamiento);
        panelAlojamiento.setLayout(panelAlojamientoLayout);
        panelAlojamientoLayout.setHorizontalGroup(
            panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlojamientoLayout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(btn_alojar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelAlojamientoLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAlojamientoLayout.createSequentialGroup()
                        .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.CENTER))
                        .addGap(725, 725, 725))
                    .addGroup(panelAlojamientoLayout.createSequentialGroup()
                        .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbx_nroid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(tbx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(panelAlojamientoLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btn_addHuesped)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7)
                            .addComponent(cbx_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_tipohabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(panelAlojamientoLayout.createSequentialGroup()
                                .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(cld_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(75, 75, 75)
                                .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(cld_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel9)
                            .addComponent(cbx_titular, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))))
        );
        panelAlojamientoLayout.setVerticalGroup(
            panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlojamientoLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlojamientoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbx_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addComponent(tbx_nroid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAlojamientoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_addHuesped)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(93, Short.MAX_VALUE))
                            .addGroup(panelAlojamientoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_alojar)
                                .addGap(72, 72, 72))))
                    .addGroup(panelAlojamientoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_hoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_tipohabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_titular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(panelAlojamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cld_llegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cld_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        cld_llegada.setMinSelectableDate(new Date(2023,04,15));
        cld_salida.setMinSelectableDate(cld_llegada.getDate() == null ? new Date(): cld_llegada.getDate());

        jTabbedPane1.addTab("Alojamiento", panelAlojamiento);

        javax.swing.GroupLayout panelServiciosLayout = new javax.swing.GroupLayout(panelServicios);
        panelServicios.setLayout(panelServiciosLayout);
        panelServiciosLayout.setHorizontalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelServiciosLayout.setVerticalGroup(
            panelServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Servicios adicionales", panelServicios);

        javax.swing.GroupLayout panelCajaLayout = new javax.swing.GroupLayout(panelCaja);
        panelCaja.setLayout(panelCajaLayout);
        panelCajaLayout.setHorizontalGroup(
            panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panelCajaLayout.setVerticalGroup(
            panelCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Caja", panelCaja);

        titulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        titulo.setText("Hoteles ComodINN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addHuespedActionPerformed
        String nombre = tbx_nombre.getText(), nroId = tbx_nroid.getText();
        Huesped huespedNuevo = new Huesped(nombre, nroId);
        txt_huespedes.append(String.format("Huesped: \nNombre: %s\nNro. Identificación: %s.\n", nombre, nroId));
        huespedes.add(huespedNuevo);
        cbx_titular.addItem(nombre);
        tbx_nombre.setText("");
        tbx_nroid.setText("");
    }//GEN-LAST:event_btn_addHuespedActionPerformed

    private void btn_alojarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alojarActionPerformed
        switch(cbx_hoteles.getSelectedIndex()) {
            case 0 -> servicio3.alojamientoInicial(huespedes, 
                    servicio3.generarHabitacion(cbx_tipohabitacion.getSelectedIndex(), 
                            cbx_hoteles.getSelectedIndex(), 
                            cbx_tipohabitacion.getSelectedIndex(), 
                            huespedes), 
                    convertirFecha(cld_llegada.getDate()), 
                    convertirFecha(cld_salida.getDate()), 
                    devolverTitular(cbx_titular.getSelectedIndex()), 
                    new ArrayList<>());
            case 1 -> servicio4.alojamientoInicial(huespedes, 
                    servicio4.generarHabitacion(cbx_tipohabitacion.getSelectedIndex(), 
                            cbx_hoteles.getSelectedIndex(), 
                            cbx_tipohabitacion.getSelectedIndex(), 
                            huespedes), 
                    convertirFecha(cld_llegada.getDate()), 
                    convertirFecha(cld_salida.getDate()), 
                    devolverTitular(cbx_titular.getSelectedIndex()), 
                    new ArrayList<>());
            case 2 -> servicio5.alojamientoInicial(huespedes, 
                    servicio5.generarHabitacion(cbx_tipohabitacion.getSelectedIndex(), 
                            cbx_hoteles.getSelectedIndex(), 
                            cbx_tipohabitacion.getSelectedIndex(), 
                            huespedes), 
                    convertirFecha(cld_llegada.getDate()), 
                    convertirFecha(cld_salida.getDate()), 
                    devolverTitular(cbx_titular.getSelectedIndex()), 
                    new ArrayList<>());
        }
        limpiarVentana();
        JOptionPane.showMessageDialog(this, "¡Su alojamiento ha sido registrado exitosamente!\nDisfrute de su estancia.");
    }//GEN-LAST:event_btn_alojarActionPerformed

    private void cld_llegadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cld_llegadaMouseClicked
       cld_salida.setMinSelectableDate(cld_llegada.getDate() == null ? new Date(): cld_llegada.getDate());
    }//GEN-LAST:event_cld_llegadaMouseClicked

    private void cld_llegadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cld_llegadaMouseExited
        cld_salida.setMinSelectableDate(cld_llegada.getDate() == null ? new Date(): cld_llegada.getDate());
    }//GEN-LAST:event_cld_llegadaMouseExited

    private void cbx_hotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_hotelesActionPerformed
        determinarHabitaciones(cbx_hoteles.getSelectedIndex());
    }//GEN-LAST:event_cbx_hotelesActionPerformed

    private void cbx_hotelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_hotelesMouseClicked
       // determinarHabitaciones(cbx_hoteles.getSelectedIndex());
    }//GEN-LAST:event_cbx_hotelesMouseClicked

    private void cbx_hotelesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbx_hotelesPropertyChange
        determinarHabitaciones(cbx_hoteles.getSelectedIndex());
    }//GEN-LAST:event_cbx_hotelesPropertyChange

    private Huesped devolverTitular(int indice) {
        return huespedes.get(indice);
    } 
    
    private LocalDate convertirFecha(Date fecha) {
        return fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    }
    
    private void determinarHabitaciones(int indiceHotel) {
        cbx_tipohabitacion.removeAllItems();
        final String[] TIPOS_HABITACION = {"Individual", "Estándar", "Suite", "Suite", "Familiar", "Presidencial", "Suite", "Deluxe", "Loft"};
        int indiceHabitacion = indiceHotel*3;
        
        for (int i = indiceHabitacion; i < indiceHabitacion+3; i++) {
            cbx_tipohabitacion.addItem(TIPOS_HABITACION[i]);
        }
    }
    
    private void limpiarVentana() {
        tbx_nombre.setText("");
        tbx_nroid.setText("");
        txt_huespedes.setText("");
        cld_llegada.setDate(null);
        cld_salida.setDate(null);
        cbx_titular.removeAllItems();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addHuesped;
    private javax.swing.JButton btn_alojar;
    private javax.swing.JComboBox<String> cbx_hoteles;
    private javax.swing.JComboBox<String> cbx_tipohabitacion;
    private javax.swing.JComboBox<String> cbx_titular;
    private com.toedter.calendar.JDateChooser cld_llegada;
    private com.toedter.calendar.JDateChooser cld_salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelAlojamiento;
    private javax.swing.JPanel panelCaja;
    private javax.swing.JPanel panelServicios;
    private javax.swing.JTextField tbx_nombre;
    private javax.swing.JTextField tbx_nroid;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextArea txt_huespedes;
    // End of variables declaration//GEN-END:variables
}
